---

hostname: nfirewall01

interfaces:
  - name: eth0
    description: "WAN - Internet"
    enabled: true
    address: dhcp
  - name: eth1
    description: "uplink - CORE"
    enabled: true
    address: 10.21.1.2/29