---

server_name: swebdmz01
domain_name: fatec.lab

nginx_version: 1.20.1

firewall_services:
  - http
  - https

sites:
  - name: web
    web_site: web.fatec.lab
    web_dir: "/var/www/web.fatec.lab/html"

interfaces:
  - name: enp1s0
    ipv4: 10.20.200.20/24
    gw4: 10.20.200.254
    dns4:
      - 10.20.200.10
    type: ethernet
    autoconnect: true
