---

server_name: "sdnsdmz01"
domain_name: "fatec.lab"

netplan_renderer: networkd
netplan_filename: 01-ansible-netcfg.yaml
interfaces:
  - name: enp1s0
    ipv4: 10.20.200.10/24
    gw4: 10.20.200.254
    dns4:
      - 10.20.200.10
    type: ethernet
    autoconnect: true

dns_serial: "{{ lookup('ansible.builtin.pipe', 'date +%Y%m%d%H') }}"

bind_cache_dir: "/var/cache/bind"

forwarders:
  - "208.67.222.222"
  - "8.8.8.8"
  - "1.1.1.1"

zone_name: "fatec.lab"

reverse_zone: "200.20.10.in-addr.arpa"

allow_query:
  - "localhost"
  - "10.0.0.0/8"

records:
  - { name: "sdnsdmz01", type: "A", value: "10.20.200.10" }
  - { name: "www", type: "A", value: "10.20.200.20" }
  - { name: "web", type: "CNAME", value: "www" }
  - { name: "teste", type: "A", value: "10.20.200.50" }
ptr_records:
  - { ip: "10", name: "sdnsdmz01.fatec.lab" }
  - { ip: "20", name: "www.fatec.lab" }
