---

- name: Instalar firewalld
  ansible.builtin.dnf:
    name:
      - firewalld
    state: present

- name: Habilitar serviço firewalld
  ansible.builtin.systemd_service:
    name: firewalld.service
    enabled: true
    state: started

- name: Configurar firewall (apenas para Rocky Linux)
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ firewall_services }}"
  when: ansible_facts['distribution'] == "Rocky"
  notify: Restart NGINX
