---

- name: Configurar o arquivo /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_facts.default_ipv4.address }} {{ server_name }}.{{ domain_name }} {{ server_name }}"

- name: Configurar o hostname
  ansible.builtin.hostname:
    name: "{{ server_name }}.{{ domain_name }}"

- name: Configurar Network
  ansible.builtin.import_tasks:
    file: network.yml

- name: Configurar Web Nginx
  ansible.builtin.import_tasks:
    file: nginx.yml

- name: Configurar Firewall
  ansible.builtin.import_tasks:
    file: firewall.yml

- name: Configurar SELinux
  ansible.builtin.import_tasks:
    file: selinux.yml
