---

- name: Configurar nome do servidor
  ansible.windows.win_hostname:
    name: "{{ server_name }}"
  register: hostname_change

- name: Reiniciar se o nome for alterado
  ansible.windows.win_reboot:
    reboot_timeout: 600
  when: hostname_change.reboot_required

- name: Configurar Domain Controller
  ansible.builtin.import_tasks: ad_ds.yml
  tags: DC

- name: Configurar DNS
  ansible.builtin.import_tasks: dns.yml
  tags: dns

- name: Configurar DHCP server
  ansible.builtin.import_tasks: dhcp.yml
  tags: dhcp

- name: Configurar usuários e grupos
  ansible.builtin.import_tasks: users_groups.yml
  tags: users
