---

- name: Configurar VyOS Firewall
  ansible.builtin.import_playbook: nfirewall01.yml

- name: Configurar VyOS Core/Distribuição
  ansible.builtin.import_playbook: ncore01.yml

- name: Configurar DNS DMZ
  ansible.builtin.import_playbook: sdnsdmz01.yml

- name: Configurar ADDC Server
  ansible.builtin.import_playbook: sdcsvr01.yml

# - name: Configurar SAMBA Server
#   ansible.builtin.import_playbook: ssambasvr01.yml

- name: Configurar Web DMZ
  ansible.builtin.import_playbook: swebdmz01.yml

- name: Configurar Clientes
  ansible.builtin.import_playbook: clientes.yml
