---

- name: Configurar clientes linux
  hosts: clientes_linux_service
  gather_facts: true
  roles:
    - clientes_linux

- name: Configurar clientes win
  hosts: clientes_win_service
  gather_facts: true
  roles:
    - clientes_win
