---

- name: Configurar o arquivo /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ server_name }}.{{ domain_name }} {{ server_name }}"
    state: present

- name: Configurar o hostname
  ansible.builtin.hostname:
    name: "{{ server_name }}.{{ domain_name }}"

- name: Configurar Bind DNS
  ansible.builtin.import_tasks:
    file: bind.yml

- name: Configurar Network
  ansible.builtin.import_tasks:
    file: network.yml
